### ISSUE TITLE
'Error: no space left on device' when trying to store the internet

### ISSUE THREAD

**Issue by Nicnl** [ravernkoh/infinite#2]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I tried to store the internet.

### What did you expect to see?

The internet stored in my infinite database.

### What did you see instead?

The internet isn't stored in my database, **AND** my system is now completely unusable.

1. I still have free space available on my disk:
(here I have 21GB available)
```
root@server:~/db# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        24G  2.6G   21G  12% /
udev             10M     0   10M   0% /dev
```

2. I'm unable to store anymore values in my infinite db:
```
root@server:~/db# infinite value db --set value

Error: open db/dmFsdWU=.0: no space left on device
```

3. I'm now unable to create files and folders across my entire system too:
```
root@server:~# mkdir test
mkdir: cannot create directory 'test': No space left on device
root@server:~# touch test
touch: cannot touch 'test': No space left on device
```

What the hell is going on?!

#### Go version

```
root@server:~# go version
mkdir /tmp/go-build613953862: no space left on device
root@server:~# go version
mkdir /tmp/go-build539574910: no space left on device
root@server:~# rm /usr/bin/perl && go version
go version go1.10.3 linux/amd64
```

#### System informations

```
-bash: perl: command not found
root@server:~# cat /etc/issue
Debian GNU/Linux 8 \n \l
```

________________________

Help would be appreciated.  
My system is completely unusable, it's pure havoc.  
I have important deadlines to meet and my entire project relies on the capabilities of this database.

**Comment by ravern** [comment]
Ah, you must be doing it wrong. You see, this database might be able to store the Internet, but are you sure your computer has enough RAM to run it?

I can give you some links to look through, but I’m afraid yours is a difficult problem to solve 😕.

http://downloadmorestorage.com
http://downloadmoreram.com
